apiVersion: v1
kind: Service
metadata:
  name: contenedor-page-load-service
spec:
  type: NodePort
  selector:
    app: contenedor-page-load
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30009